### PR TITLE
Add more complicated namespace test

### PR DESCRIPTION
**Pull request by bpowers**
This currently fails on master, as closing tags doesn't work properly.

### CODE REVIEW

**Comment by Ygg01** [comment]
Thanks for PR.

I have to ask, why is there  an `n1` namespace if it isn't used for anything? Does it serve some purpose in tests?

**Comment by bpowers** [comment]
@Ygg01 aah, nope!  I just did a bad copy-paste job from the previous test.  I've removed it in a follow-up commit, let me know if you want me to squash them together.

**Comment by Ygg01** [comment]
Sure, just squash them. I apologize for the delay in reviewing/merging, I'll get to it later this evening.

**Comment by bpowers** [comment]
squashed.  no worries!

**Comment by Ygg01** [comment]
Seems good. Merging.

**Comment by bpowers** [comment]
thanks!

**Pull request merged**
